local localization = {
	mod_title = { en = "Damage Tracker", ["zh-cn"] = "伤害追踪器" },
	mod_description = { en = "Tracks damage on your HUD with static totals and floating combat text.", ["zh-cn"] = "在HUD上追踪你的战术伤害总计，并提供动态浮动战斗文本。" },

	main_tracking_setting = { en = "Static Damage Tracking (Totals)", ["zh-cn"] = "面板伤害追踪 (总计数据)" },
	tracking_mode = { en = "Tracking Mode", ["zh-cn"] = "追踪模式" },
	display_format = { en = "Display Format", ["zh-cn"] = "显示格式" },
	main_text_size = { en = "Unified Text Size", ["zh-cn"] = "统一字体大小" },
	main_x = { en = "Panel X Position", ["zh-cn"] = "面板 X 轴位置" },
	main_y = { en = "Panel Y Position", ["zh-cn"] = "面板 Y 轴位置" },

	mode_combined = { en = "Combined (Default)", ["zh-cn"] = "默认 (直伤和DoT合并计算)" },
	mode_separated = { en = "Separated (Two Lines)", ["zh-cn"] = "分离 (直伤+DoT 双行显示)" },
	mode_direct_only = { en = "Direct Only", ["zh-cn"] = "仅直伤" },
	mode_dot_only = { en = "DoT Only", ["zh-cn"] = "仅DoT" },

	combined_color = { en = "[Combined] Color", ["zh-cn"] = "[合并计算] 颜色" },
	combined_icon = { en = "[Combined] Icon", ["zh-cn"] = "[合并计算] 图标" },
	direct_color = { en = "[Direct] Color", ["zh-cn"] = "[直伤] 颜色" },
	direct_icon = { en = "[Direct] Icon", ["zh-cn"] = "[直伤] 图标" },
	dot_color = { en = "[DoT] Color", ["zh-cn"] = "[DoT] 颜色" },
	dot_icon = { en = "[DoT] Icon", ["zh-cn"] = "[DoT] 图标" },

	floating_text_setting = { en = "Floating Combat Text (FCT)", ["zh-cn"] = "浮动战斗文本 (FCT)" },
	floating_mode = { en = "FCT Mode", ["zh-cn"] = "显示模式" },
	floating_style = { en = "Animation Style", ["zh-cn"] = "动画形式" },
	fct_style_fixed = { en = "Fixed Aggregation", ["zh-cn"] = "固定" },
	fct_style_compact = { en = "Compact", ["zh-cn"] = "简洁" },
	fct_style_float = { en = "Float Up", ["zh-cn"] = "上浮" },

	floating_weapon_filter = { en = "Weapon Filter", ["zh-cn"] = "武器过滤" },
	floating_x = { en = "FCT Origin X", ["zh-cn"] = "浮动起始 X 位置" },
	floating_y = { en = "FCT Origin Y", ["zh-cn"] = "浮动起始 Y 位置" },
	fct_offset_head = { en = "FCT Head Offset", ["zh-cn"] = "浮动头部偏移" },
	fct_offset_body = { en = "FCT Body Offset", ["zh-cn"] = "浮动身体偏移" },
	fct_distance_scaling = { en = "Distance Scaling", ["zh-cn"] = "距离缩放" },
	fct_distance_reference = { en = "Reference Distance", ["zh-cn"] = "参考距离" },
	fct_los_check = { en = "Wall Inspection", ["zh-cn"] = "墙体检测" },

	fct_enemy_filter = { en = "Enemy Type Filter", ["zh-cn"] = "敌人类型筛选" },
	fct_enemy_filters = { en = "Enemy Type Filter", ["zh-cn"] = "敌人类型筛选" },

	fct_general = { en = "General", ["zh-cn"] = "常规设置" },
	fct_hit_types = { en = "Hit Type Filter", ["zh-cn"] = "伤害类型筛选" },
	fct_show_normal = { en = "Normal Hits", ["zh-cn"] = "普通伤害" },
	fct_show_pure_weakspot = { en = "Weakspot Hits", ["zh-cn"] = "弱点伤害 (非暴击)" },
	fct_show_pure_crit = { en = "Crit Hits", ["zh-cn"] = "暴击伤害 (非弱点)" },
	fct_show_weakspot_crit = { en = "Weakspot + Crit", ["zh-cn"] = "弱点暴击" },
	fct_show_dot = { en = "DoT Ticks", ["zh-cn"] = "持续伤害 (DoT)" },
	fct_show_explosion = { en = "Explosion Hits", ["zh-cn"] = "爆炸伤害" },
	fct_damage_threshold = { en = "Damage Threshold (0=off)", ["zh-cn"] = "伤害过滤阈值 (0=关闭)" },
	fct_fixed_mode = { en = "Fixed Style", ["zh-cn"] = "固定风格" },
	fct_compact_mode = { en = "Compact Style", ["zh-cn"] = "简洁风格" },

	fixed_style_normal = { en = "Style: Normal Hit", ["zh-cn"] = "样式: 普通直伤" },
	fixed_style_dot = { en = "Style: DoT Tick", ["zh-cn"] = "样式: DoT" },
	fixed_style_pure_crit = { en = "Style: Pure Crit", ["zh-cn"] = "样式: 非弱点暴击" },
	fixed_style_pure_weakspot = { en = "Style: Pure Weakspot", ["zh-cn"] = "样式: 弱点伤害" },
	fixed_style_weakspot_crit = { en = "Style: Weakspot + Crit", ["zh-cn"] = "样式: 弱点暴击" },
	compact_style_normal = { en = "Style: Normal Hit", ["zh-cn"] = "样式: 普通直伤" },
	compact_style_dot = { en = "Style: DoT Tick", ["zh-cn"] = "样式: DoT" },
	compact_style_pure_crit = { en = "Style: Pure Crit", ["zh-cn"] = "样式: 非弱点暴击" },
	compact_style_pure_weakspot = { en = "Style: Pure Weakspot", ["zh-cn"] = "样式: 弱点伤害" },
	compact_style_weakspot_crit = { en = "Style: Weakspot + Crit", ["zh-cn"] = "样式: 弱点暴击" },
	fct_show_horde = { en = "Show Horde/Roamer Damage", ["zh-cn"] = "显示尸潮/杂兵敌人伤害" },
	fct_show_elite = { en = "Show Elite Damage", ["zh-cn"] = "显示精英敌人伤害" },
	fct_show_special = { en = "Show Specialist Damage", ["zh-cn"] = "显示专家敌人伤害" },
	fct_show_boss = { en = "Show Boss Damage", ["zh-cn"] = "显示Boss单位伤害" },
	fct_show_other = { en = "Show Other Unknown Damage", ["zh-cn"] = "显示其他未知敌人伤害" },
	font_machine_medium = { en = "Machine Medium Bold", ["zh-cn"] = "粗体机械风格" },
	font_proxima_nova_bold = { en = "Proxima Nova Bold", ["zh-cn"] = "粗体" },
	font_proxima_nova_medium = { en = "Proxima Nova Medium", ["zh-cn"] = "常规" },
	font_mono_tide_bold = { en = "Mono Tide Bold", ["zh-cn"] = "等宽粗体" },
	font_mono_tide_medium = { en = "Mono Tide Medium", ["zh-cn"] = "等宽中等" },
	font_itc_novarese_bold = { en = "ITC Novarese Bold", ["zh-cn"] = "衬线粗体" },
	font_arial = { en = "Arial", ["zh-cn"] = "Arial" },
	fct_font_type = { en = "Font Type", ["zh-cn"] = "字体样式" },
	main_font_type = { en = "Font Type", ["zh-cn"] = "字体样式" },

	weapon_filter_both = { en = "Both Melee & Ranged", ["zh-cn"] = "默认 (近战与远程)" },
	weapon_filter_melee = { en = "Melee Only", ["zh-cn"] = "仅限近战" },
	weapon_filter_ranged = { en = "Ranged Only", ["zh-cn"] = "仅限远程" },

	-- Fixed mode style settings
	fixed_normal_color = { en = "[Normal] Color", ["zh-cn"] = "[普通直伤] 颜色" },
	fixed_normal_size = { en = "[Normal] Base Size", ["zh-cn"] = "[普通直伤] 基础字号" },
	fixed_normal_icon = { en = "[Normal] Icon", ["zh-cn"] = "[普通直伤] 图标" },
	fixed_dot_color = { en = "[DoT] Color", ["zh-cn"] = "[DoT] 颜色" },
	fixed_dot_size = { en = "[DoT] Base Size", ["zh-cn"] = "[DoT] 基础字号" },
	fixed_dot_icon = { en = "[DoT] Icon", ["zh-cn"] = "[DoT] 图标" },
	fixed_pure_crit_color = { en = "[Crit] Color", ["zh-cn"] = "[非弱点暴击] 颜色" },
	fixed_pure_crit_size = { en = "[Crit] Base Size", ["zh-cn"] = "[非弱点暴击] 基础字号" },
	fixed_pure_crit_icon = { en = "[Crit] Icon", ["zh-cn"] = "[非弱点暴击] 图标" },
	fixed_pure_weakspot_color = { en = "[Weakspot] Color", ["zh-cn"] = "[弱点] 颜色" },
	fixed_pure_weakspot_size = { en = "[Weakspot] Base Size", ["zh-cn"] = "[弱点] 基础字号" },
	fixed_pure_weakspot_icon = { en = "[Weakspot] Icon", ["zh-cn"] = "[弱点] 图标" },
	fixed_weakspot_crit_color = { en = "[Weakspot+Crit] Color", ["zh-cn"] = "[弱点暴击] 颜色" },
	fixed_weakspot_crit_size = { en = "[Weakspot+Crit] Base Size", ["zh-cn"] = "[弱点暴击] 基础字号" },
	fixed_explosion_color = { en = "[Explosion] Color", ["zh-cn"] = "[爆炸] 颜色" },
	fixed_explosion_size = { en = "[Explosion] Base Size", ["zh-cn"] = "[爆炸] 基础字号" },
	fixed_explosion_icon = { en = "[Explosion] Icon", ["zh-cn"] = "[爆炸] 图标" },
	fixed_weakspot_crit_icon = { en = "[Weakspot+Crit] Icon", ["zh-cn"] = "[弱点暴击] 图标" },

	-- Compact mode style settings
	compact_normal_color = { en = "[Normal] Color", ["zh-cn"] = "[普通直伤] 颜色" },
	compact_normal_size = { en = "[Normal] Base Size", ["zh-cn"] = "[普通直伤] 基础字号" },
	compact_normal_icon = { en = "[Normal] Icon", ["zh-cn"] = "[普通直伤] 图标" },
	compact_dot_color = { en = "[DoT] Color", ["zh-cn"] = "[DoT] 颜色" },
	compact_dot_size = { en = "[DoT] Base Size", ["zh-cn"] = "[DoT] 基础字号" },
	compact_dot_icon = { en = "[DoT] Icon", ["zh-cn"] = "[DoT] 图标" },
	compact_pure_crit_color = { en = "[Crit] Color", ["zh-cn"] = "[非弱点暴击] 颜色" },
	compact_pure_crit_size = { en = "[Crit] Base Size", ["zh-cn"] = "[非弱点暴击] 基础字号" },
	compact_pure_crit_icon = { en = "[Crit] Icon", ["zh-cn"] = "[非弱点暴击] 图标" },
	compact_pure_weakspot_color = { en = "[Weakspot] Color", ["zh-cn"] = "[弱点] 颜色" },
	compact_pure_weakspot_size = { en = "[Weakspot] Base Size", ["zh-cn"] = "[弱点] 基础字号" },
	compact_pure_weakspot_icon = { en = "[Weakspot] Icon", ["zh-cn"] = "[弱点] 图标" },
	compact_weakspot_crit_color = { en = "[Weakspot+Crit] Color", ["zh-cn"] = "[弱点暴击] 颜色" },
	compact_weakspot_crit_size = { en = "[Weakspot+Crit] Base Size", ["zh-cn"] = "[弱点暴击] 基础字号" },
	compact_explosion_color = { en = "[Explosion] Color", ["zh-cn"] = "[爆炸] 颜色" },
	compact_explosion_size = { en = "[Explosion] Base Size", ["zh-cn"] = "[爆炸] 基础字号" },
	compact_explosion_icon = { en = "[Explosion] Icon", ["zh-cn"] = "[爆炸] 图标" },
	compact_weakspot_crit_icon = { en = "[Weakspot+Crit] Icon", ["zh-cn"] = "[弱点暴击] 图标" },

	-- Float mode
	fct_float_mode = { en = "Float Up Style", ["zh-cn"] = "上浮风格" },
	float_head_offset = { en = "Head Vertical Offset", ["zh-cn"] = "头部垂直偏移" },
	float_body_offset = { en = "Body Vertical Offset", ["zh-cn"] = "身体垂直偏移" },
	float_dot_offset = { en = "DoT Vertical Offset", ["zh-cn"] = "DoT垂直偏移" },
	float_distance_scaling = { en = "Distance Size Scaling", ["zh-cn"] = "字号距离缩放" },
	float_los_check = { en = "Wall Inspection", ["zh-cn"] = "墙体检测" },
	float_normal_color = { en = "[Normal] Color", ["zh-cn"] = "[普通直伤] 颜色" },
	float_normal_size = { en = "[Normal] Base Size", ["zh-cn"] = "[普通直伤] 基础字号" },
	float_normal_icon = { en = "[Normal] Icon", ["zh-cn"] = "[普通直伤] 图标" },
	float_dot_color = { en = "[DoT] Color", ["zh-cn"] = "[DoT] 颜色" },
	float_dot_size = { en = "[DoT] Base Size", ["zh-cn"] = "[DoT] 基础字号" },
	float_dot_icon = { en = "[DoT] Icon", ["zh-cn"] = "[DoT] 图标" },
	float_pure_crit_color = { en = "[Crit] Color", ["zh-cn"] = "[非弱点暴击] 颜色" },
	float_pure_crit_size = { en = "[Crit] Base Size", ["zh-cn"] = "[非弱点暴击] 基础字号" },
	float_pure_crit_icon = { en = "[Crit] Icon", ["zh-cn"] = "[非弱点暴击] 图标" },
	float_pure_weakspot_color = { en = "[Weakspot] Color", ["zh-cn"] = "[弱点] 颜色" },
	float_pure_weakspot_size = { en = "[Weakspot] Base Size", ["zh-cn"] = "[弱点] 基础字号" },
	float_pure_weakspot_icon = { en = "[Weakspot] Icon", ["zh-cn"] = "[弱点] 图标" },
	float_weakspot_crit_color = { en = "[Weakspot+Crit] Color", ["zh-cn"] = "[弱点暴击] 颜色" },
	float_weakspot_crit_size = { en = "[Weakspot+Crit] Base Size", ["zh-cn"] = "[弱点暴击] 基础字号" },
	float_explosion_color = { en = "[Explosion] Color", ["zh-cn"] = "[爆炸] 颜色" },
	float_explosion_size = { en = "[Explosion] Base Size", ["zh-cn"] = "[爆炸] 基础字号" },
	float_explosion_icon = { en = "[Explosion] Icon", ["zh-cn"] = "[爆炸] 图标" },
	float_weakspot_crit_icon = { en = "[Weakspot+Crit] Icon", ["zh-cn"] = "[弱点暴击] 图标" },

	mode_disabled = { en = "Disabled", ["zh-cn"] = "禁用" },
	mode_total_only = { en = "Total Only", ["zh-cn"] = "仅显示总计" },
	mode_single_only = { en = "Single Hit Only", ["zh-cn"] = "仅显示单次" },
	mode_both = { en = "Total + Single Hit", ["zh-cn"] = "总计 + 单次" },

	enable_overkill_damage = { en = "Damage settlement includes overkill", ["zh-cn"] = "伤害结算包含溢出伤害" },
	use_k_format = { en = "Use K-Format (e.g. 1.2k)", ["zh-cn"] = "使用K格式缩写 (如 1.2k)" },

	icon_none = { en = "None", ["zh-cn"] = "无" },
	icon_weapons = { en = "Weapons", ["zh-cn"] = "武器" },
	icon_difficulty_skull_heresy = { en = "Trimmed Skull", ["zh-cn"] = "边饰颅骨" },
	icon_difficulty_skull_uprising = { en = "Skull", ["zh-cn"] = "头骨" },
	icon_objective_main = { en = "Ball Spur", ["zh-cn"] = "球刺" },
	icon_incapacitated = { en = "Exclamation", ["zh-cn"] = "感叹号" },
	icon_dead = { en = "Deadly Skull", ["zh-cn"] = "致命头骨" },
	icon_pocketable_syringe_power = { en = "Brain Burst", ["zh-cn"] = "脑部爆裂" },
	icon_scars = { en = "Scars", ["zh-cn"] = "爪痕" },
	icon_mission_type_01 = { en = "Blade", ["zh-cn"] = "利刃" },
	icon_preset_19 = { en = "Boom", ["zh-cn"] = "爆炸" },
}
return localization
